# Eat Safe, Love

## Notebook Set Up

In [19]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [20]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [21]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [22]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [23]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [24]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
hygiene_score = establishments.find(query)
# Use count_documents to display the number of documents in the result
print("Number of documents with score of 20:", establishments.count_documents(query))
# Display the first document in the results using pprint
pprint(hygiene_score[0])

Number of documents with score of 20: 41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65a86d8ff4c730302e0746cf'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [25]:
# Convert the result to a Pandas DataFrame
import pandas as pd 
hygiene_score_df = pd.json_normalize(hygiene_score)

# Display the number of rows in the DataFrame
print(len(hygiene_score_df))
# Display the first 10 rows of the DataFrame
hygiene_score_df.head(10)

41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,65a86d8ff4c730302e0746cf,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,65a86d90f4c730302e074a4e,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,65a86d90f4c730302e074d53,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,65a86d90f4c730302e074f3f,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,65a86d90f4c730302e074f59,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,65a86d90f4c730302e0758f2,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,65a86d90f4c730302e075b14,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,65a86d90f4c730302e077042,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,65a86d90f4c730302e077484,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,65a86d90f4c730302e077c96,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [26]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
# query = {'RatingValue': {'$gte':4}
query = {'$and': [
    {'LocalAuthorityName': {'$regex':'London', '$options': 'i'}},
    {'RatingValue' : {'$gte':4}}]}
# Use count_documents to display the number of documents in the result
print('The number of documents meeting the above criteria is:', establishments.count_documents(query))
# Display the first document in the results using pprint

pprint(establishments.find_one(query))

The number of documents meeting the above criteria is: 33
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65a86d90f4c730302e0760e8'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [27]:
# Convert the result to a Pandas DataFrame

london_df = pd.json_normalize(establishments.find(query))

# Display the number of rows in the DataFrame
print(len(london_df))
# Display the first 10 rows of the DataFrame
london_df.head(10)

33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,65a86d90f4c730302e0760e8,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,65a86d90f4c730302e07640c,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249256,51.123623,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,65a86d90f4c730302e076f5b,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,65a86d90f4c730302e077d5b,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346337,51.464066,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,65a86d90f4c730302e077d5c,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,65a86d90f4c730302e078464,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,65a86d90f4c730302e07a572,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.069286,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,65a86d90f4c730302e07a93f,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.048006,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,65a86d90f4c730302e07a950,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,65a86d90f4c730302e07a951,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [29]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

# Define the search parameters
degree_search = 0.01
latitude = 51.490142  # Latitude of Penang Flavours
longitude = 0.08384   # Longitude of Penang Flavours

# Construct the query
query = {
    "RatingValue": 5,
    "geocode.latitude": {"$gte": latitude - degree_search, "$lte": latitude + degree_search},
    "geocode.longitude": {"$gte": longitude - degree_search, "$lte": longitude + degree_search}
}

# Define the sorting order by hygiene score
sort = [("HygieneScore", 1)]  # Replace 'HygieneScore' with the actual field name if different

# Execute the query and sort the results
results = list(establishments.find(query).sort(sort).limit(5))

# Print the results
for result in results:
    print(result)

{'_id': ObjectId('65a86d90f4c730302e079f0b'), 'FHRSID': 1380578, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': '14425', 'BusinessName': 'Howe and Co Fish and Chips - Van 17', 'BusinessType': 'Mobile caterer', 'BusinessTypeID': 7846, 'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1SE', 'Phone': '', 'RatingValue': 5, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-11-11T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0925370007753372, 'latitude': 51.4875335693359}, 'RightToReply': '', 'Distance': 4646.95593107927, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/1380578'}]}
{'_id': ObjectId('65a86d90f4c730302e079f41'), 'FHRSID': 695241, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000179088', 'BusinessName': 'Plumstead Manor Nursery', 'BusinessType': 'Caring Premises', 'BusinessTypeID': 5, 'AddressLine1': 'Plumstead Manor School Old Mill Road', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1QG', 'Phone': '', 'RatingValue': 5, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-06-16T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 5}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0859939977526665, 'latitude': 51.481517791748}, 'RightToReply': '', 'Distance': 4646.9740101340385, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/695241'}]}
{'_id': ObjectId('65a86d90f4c730302e079ed2'), 'FHRSID': 1069652, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000206841', 'BusinessName': 'TIWA N TIWA African Restaurant Ltd', 'BusinessType': 'Restaurant/Cafe/Canteen', 'BusinessTypeID': 1, 'AddressLine1': '152 Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1JQ', 'Phone': '', 'RatingValue': 5, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2020-10-24T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 5, 'Structural': 5, 'ConfidenceInManagement': 5}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0927429, 'latitude': 51.4870351}, 'RightToReply': '', 'Distance': 4646.930146257832, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/1069652'}]}
{'_id': ObjectId('65a86d90f4c730302e079f01'), 'FHRSID': 695223, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000178842', 'BusinessName': 'Iceland', 'BusinessType': 'Retailers - supermarkets/hypermarkets', 'BusinessTypeID': 7840, 'AddressLine1': '144 - 146 Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1JQ', 'Phone': '', 'RatingValue': 5, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2019-11-13T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 5, 'ConfidenceInManagement': 5}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0924199968576431, 'latitude': 51.4871482849121}, 'RightToReply': '', 'Distance': 4646.946071297699, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/695223'}]}
{'_id': ObjectId('65a86d90f4c730302e079f2b'), 'FHRSID': 694609, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000116619', 'BusinessName': 'Volunteer', 'BusinessType': 'Pub/bar/nightclub', 'BusinessTypeID': 7843, 'AddressLine1': '130 - 132 Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1JQ', 'Phone': '', 'RatingValue': 5, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2019-08-05T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.09208, 'latitude': 51.4873437}, 'RightToReply': '', 'Distance': 4646.965634598608, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/694609'}]}

In [30]:
# Convert result to Pandas DataFrame
# Convert the query result to a Pandas DataFrame
establishments_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print(f"Number of rows in DataFrame: {len(establishments_df)}")

# Display the first few rows of the DataFrame
establishments_df.head()

Number of rows in DataFrame: 5

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65a86d90f4c730302e079f0b,1380578,0,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,7846,Restaurant And Premises 107A Plumstead High St...,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0925370007753372, 'latitude': ...",,4646.955931,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,65a86d90f4c730302e079f41,695241,0,PI/000179088,Plumstead Manor Nursery,Caring Premises,5,Plumstead Manor School Old Mill Road,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0859939977526665, 'latitude': ...",,4646.974010,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,65a86d90f4c730302e079ed2,1069652,0,PI/000206841,TIWA N TIWA African Restaurant Ltd,Restaurant/Cafe/Canteen,1,152 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0927429, 'latitude': 51.4870351}",,4646.930146,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,65a86d90f4c730302e079f01,695223,0,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,7840,144 - 146 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0924199968576431, 'latitude': ...",,4646.946071,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,65a86d90f4c730302e079f2b,694609,0,PI/000116619,Volunteer,Pub/bar/nightclub,7843,130 - 132 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.09208, 'latitude': 51.4873437}",,4646.965635,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [34]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {"$match": {"scores.Hygiene": 0}}

# 2. Groups the matches by Local Authority
group_query = {
    "$group": {
        "_id": "$LocalAuthorityName",
        "count": {"$sum": 1}
    }
}

# 3. Sorts the matches from highest to lowest
sort_values = {"$sort": {"count": -1}}

# Create the pipeline
pipeline = [match_query, group_query, sort_values]

# Execute the pipeline
results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print("Total number of documents is:", len(results))

# Print the first 10 results
for result in results[:10]:
    print(result)

Total number of documents is: 55
{'_id': 'Thanet', 'count': 1130}
{'_id': 'Greenwich', 'count': 882}
{'_id': 'Maidstone', 'count': 713}
{'_id': 'Newham', 'count': 711}
{'_id': 'Swale', 'count': 686}
{'_id': 'Chelmsford', 'count': 680}
{'_id': 'Medway', 'count': 672}
{'_id': 'Bexley', 'count': 607}
{'_id': 'Southend-On-Sea', 'count': 586}
{'_id': 'Tendring', 'count': 542}

In [35]:
# Convert the query result to a Pandas DataFrame
establishments_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print(f"Number of rows in DataFrame: {len(establishments_df)}")

# Display the first 10 rows of the DataFrame
establishments_df.head(10)

Number of rows in DataFrame: 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542